export const Route = {
  main: '/',
  tokenValue: '/?token=:tokenValue',
  about: '/about',
  rules: '/rules',
  delivery: '/delivery',
  payment: '/payment',
  registration: '/registration',
  product: '/product',
  id: '/product/:id',
  description: '/product/:id/description',
  constitution: '/product/:id/constitution',
  feedback: '/product/:id/feedback',
  questions: '/product/:id/questions',
  dashboard: {
    myPage: '/dashboard/myPage',
    addProduct: '/dashboard/add-product',
    myTemplates: '/dashboard/templates',
    myProducts: '/dashboard/products',
    mySales: '/dashboard/mySales',
    myPurchases: '/dashboard/myPurchases',
    myFavorites: '/dashboard/myFavorites',
    reviews: '/dashboard/reviews',
    publicMessages: '/dashboard/publicMessages',
    privateMessages: '/dashboard/privateMessages',
  },
};
