export const Route = {
  main: '/',
  tokenValue: '/?token=:tokenValue',
  about: '/about',
  rules: '/rules',
  delivery: '/delivery',
  payment: '/payment',
  registration: '/registration',
  myPage: '/myPage',
  myPurchases: '/myPurchases',
  myFavorites: '/myFavorites',
  reviews: '/reviews',
  privateMessages: '/privateMessages',
  product: '/product',
  id: '/product/:id',
  description: '/product/:id/description',
  constitution: '/product/:id/constitution',
  feedback: '/product/:id/feedback',
  questions: '/product/:id/questions',

};
